version: '3'
services:
  postgres:
    logging:
      driver: none
    image: postgis/postgis:12-2.5
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  django:
    build:
      context: .
      dockerfile: ./django.Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    tty: true
    env_file: ./.env.docker-compose
    volumes:
      - .:/opt/django-project
    ports:
      - 8000:8000
    depends_on:
      - postgres

  yarn:
    image: node:18
    working_dir: /web
    volumes:
      - ./web:/web
    command: yarn serve
    ports:
      - 8081:8080
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
