# Generated by Django 3.2.13 on 2022-06-03 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('state_id', models.CharField(max_length=2)),
                ('county_fips', models.IntegerField()),
                ('county_name', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('density', models.IntegerField()),
                ('military', models.BooleanField()),
                ('incorporated', models.BooleanField()),
                ('timezone', models.CharField(max_length=255)),
                ('ranking', models.IntegerField()),
                ('zips', models.CharField(max_length=255)),
            ],
        ),
    ]
