# Generated by Django 3.2.13 on 2022-06-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_basic_city_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='average_wages_and_salaries',
            field=models.IntegerField(default=0, help_text='Average wages and salaries in dollars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='per_capita_dividends_interest_and_rent',
            field=models.IntegerField(default=0, help_text='Per capita dividends, interest, and rent in dollars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='per_capita_net_earnings',
            field=models.IntegerField(default=0, help_text='Per capita net earnings in dollars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='per_capita_personal_income',
            field=models.IntegerField(default=0, help_text='Per capita personal income in dollars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_employment',
            field=models.IntegerField(default=0, help_text='Total Full-Time and Part-Time Employment by NAICS Industry in number of jobs'),
            preserve_default=False,
        ),
    ]
