# Generated by Django 3.2.13 on 2022-06-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_longer_zips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='location',
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
