# Generated by Django 3.2.13 on 2022-06-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_separate_lat_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='male_female_ratio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='median_age',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='percentage_asian',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='percentage_black',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='percentage_hispanic_latino',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='percentage_native_american',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='percentage_white',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
